# Generated by Django 3.1.5 on 2021-01-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
