# Generated by Django 3.1.5 on 2021-01-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Art',
        ),
    ]
