# Generated by Django 3.1.5 on 2021-02-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210125_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='project_type',
            new_name='art_type',
        ),
    ]
