# Generated by Django 3.1.5 on 2021-07-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210215_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.IntegerField(choices=[(1, 'Indoor'), (2, 'Outdoor')], default=1),
        ),
    ]
